name: Weekly Progress Report

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  generate-report:
    name: Generate Weekly Progress Report
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub
      
      - name: Generate progress report
        id: report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          PROJECT_NUMBER: ${{ secrets.PROJECT_NUMBER }}
        run: |
          python scripts/generate_sample_report.py docs/progress_$(date +"%Y-%U").md
      
      - name: Upload report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: progress-report
          path: docs/progress_*.md
      
      - name: Create PR with progress report
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add weekly progress report"
          title: "Weekly Progress Report - $(date +"%Y Week %U")"
          body: |
            Automated weekly progress report generated on $(date +"%Y-%m-%d").
            
            This report includes:
            - Issues closed
            - PRs merged
            - Deployments
            - Average lead time
            - Risk engine status
          branch: progress-report-$(date +"%Y-%U")
          base: main
          path: docs/
      
      - name: Comment on PR
        if: steps.create-pr.outputs.pull-request-number
        run: |
          echo "Weekly progress report generated successfully!"
          echo "PR: ${{ steps.create-pr.outputs.pull-request-url }}"
